// Generated by js_of_ocaml
//# buildInfo:effects=false, kind=cma, use-js-string=true, version=5.6.0

//# unitInfo: Provides: Ptime_clock
//# unitInfo: Requires: Ptime
(function
  (globalThis){
   "use strict";
   var runtime = globalThis.jsoo_runtime;
   function caml_call1(f, a0){
    return (f.l >= 0 ? f.l : f.l = f.length) == 1
            ? f(a0)
            : runtime.caml_call_gen(f, [a0]);
   }
   var
    global_data = runtime.caml_get_global_data(),
    Ptime = global_data.Ptime;
   function now(param){
    var _e_ = runtime.ocaml_ptime_clock_now_d_ps(0);
    return caml_call1(Ptime[8], _e_);
   }
   function period(param){
    var _d_ = runtime.ocaml_ptime_clock_period_d_ps(0);
    return caml_call1(Ptime[1][5], _d_);
   }
   function current_tz_offset_s(_c_){
    return runtime.ocaml_ptime_clock_current_tz_offset_s(_c_);
   }
   function now_d_ps(_b_){return runtime.ocaml_ptime_clock_now_d_ps(_b_);}
   function period_d_ps(_a_){
    return runtime.ocaml_ptime_clock_period_d_ps(_a_);
   }
   var
    Ptime_clock = [0, now, period, current_tz_offset_s, now_d_ps, period_d_ps];
   runtime.caml_register_global(1, Ptime_clock, "Ptime_clock");
   return;
  }
  (globalThis));

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLjAsImZpbGUiOiJwdGltZV9jbG9jay5jbWEuanMiLCJzb3VyY2VSb290IjoiIiwibmFtZXMiOltdLCJzb3VyY2VzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7OztHOzs7Ozs7Ozs7SSxVO0ksTztHOztJLFU7SSxPO0c7O0k7OzBCOztJOzs7Ozs7RSIsInNvdXJjZXNDb250ZW50IjpbXX0=
