// Generated by js_of_ocaml
//# buildInfo:effects=false, kind=cma, use-js-string=true, version=5.6.0

//# unitInfo: Provides: Heap_block
//# unitInfo: Requires: Base, Base__Word_size, Ppx_bench_lib__Benchmark_accumulator, Ppx_expect_runtime, Ppx_inline_test_lib, Ppx_module_timer_runtime
(function
  (globalThis){
   "use strict";
   var
    runtime = globalThis.jsoo_runtime,
    cst_Heap_block$0 = "Heap_block",
    cst_heap_block$0 = "heap_block";
   function caml_call1(f, a0){
    return (f.l >= 0 ? f.l : f.l = f.length) == 1
            ? f(a0)
            : runtime.caml_call_gen(f, [a0]);
   }
   function caml_call2(f, a0, a1){
    return (f.l >= 0 ? f.l : f.l = f.length) == 2
            ? f(a0, a1)
            : runtime.caml_call_gen(f, [a0, a1]);
   }
   var
    global_data = runtime.caml_get_global_data(),
    Base = global_data.Base,
    Ppx_module_timer_runtime = global_data.Ppx_module_timer_runtime,
    Ppx_bench_lib_Benchmark_accumu =
      global_data.Ppx_bench_lib__Benchmark_accumulator,
    Ppx_expect_runtime = global_data.Ppx_expect_runtime,
    Ppx_inline_test_lib = global_data.Ppx_inline_test_lib,
    Base_Word_size = global_data.Base__Word_size;
   caml_call1(Ppx_module_timer_runtime[4], cst_Heap_block$0);
   caml_call1(Ppx_bench_lib_Benchmark_accumu[1][1], cst_heap_block$0);
   caml_call1(Ppx_expect_runtime[1][1], "heap_block/heap_block.ml");
   caml_call2(Ppx_inline_test_lib[6], cst_heap_block$0, "heap_block.ml");
   var
    cst_Heap_block_create_exn_call =
      "Heap_block.create_exn called with non heap block",
    cst_heap_block = cst_heap_block$0,
    cst_Heap_block = cst_Heap_block$0;
   function sexp_of_t(of_a_001){return of_a_001;}
   function create(v){
    return runtime.core_heap_block_is_heap_block(v) ? [0, v] : 0;
   }
   function create_exn(v){
    return runtime.core_heap_block_is_heap_block(v)
            ? v
            : caml_call1(Base[244], cst_Heap_block_create_exn_call);
   }
   function value(t){return t;}
   var
    bytes_per_word = caml_call1(Base_Word_size[2], Base_Word_size[3]) / 8 | 0;
   function bytes(t){
    return runtime.caml_mul(t.length - 1 + 1 | 0, bytes_per_word);
   }
   caml_call1(Ppx_inline_test_lib[7], cst_heap_block);
   caml_call1(Ppx_expect_runtime[1][2], 0);
   caml_call1(Ppx_bench_lib_Benchmark_accumu[1][2], 0);
   caml_call1(Ppx_module_timer_runtime[5], cst_Heap_block);
   var Heap_block = [0, sexp_of_t, create, create_exn, value, bytes];
   runtime.caml_register_global(14, Heap_block, cst_Heap_block$0);
   return;
  }
  (globalThis));

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLjAsImZpbGUiOiJoZWFwX2Jsb2NrLmNtYS5qcyIsInNvdXJjZVJvb3QiOiIiLCJuYW1lcyI6WyJzZXhwX29mX3QiLCJvZl9hXzAwMSIsImNyZWF0ZSIsInYiLCJjcmVhdGVfZXhuIiwidmFsdWUiLCJ0IiwiYnl0ZXNfcGVyX3dvcmQiLCJieXRlcyJdLCJzb3VyY2VzIjpbIi9ob21lL2xpYW0tY2FycGVudGVyLy5vcGFtL3BlcnNvbmFsLXNpdGUvbGliL2NvcmUvaGVhcF9ibG9jay9oZWFwX2Jsb2NrLm1sIl0sIm1hcHBpbmdzIjoiOzs7Ozs7Ozs7Ozs7Rzs7Ozs7Rzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7R0FFQSxTQUFBQSxVQUFLQyxVQUFMLE9BQUtBLFNBQThCO1lBTS9CQyxPQUFPQztJQUFJLE9BQUcsc0NBQVBBLFNBQUFBO0dBQW9DO1lBRTNDQyxXQUFXRDtJQUNiLE9BQUcsc0NBRFVBO2NBQUFBO2NBQ1U7R0FBMkQ7WUFHaEZFLE1BQU1DLEdBQUksT0FBSkEsRUFBSztHQUNpQjtJQUE1QkMsaUJBQTRCO1lBRTVCQyxNQUFnQkY7SUFDbEIsd0JBRGtCQSxzQkFGaEJDO0dBR2dFOzs7Ozt3QkFoQnBFUCxXQU1JRSxRQUVBRSxZQUlBQyxPQUdBRzs7O0UiLCJzb3VyY2VzQ29udGVudCI6WyJvcGVuISBCYXNlXG5cbnR5cGUgJ2EgdCA9ICdhIFtAQGRlcml2aW5nIHNleHBfb2ZdXG5cbmV4dGVybmFsIGlzX2hlYXBfYmxvY2sgOiBTdGRsaWIuT2JqLnQgLT4gYm9vbCA9IFwiY29yZV9oZWFwX2Jsb2NrX2lzX2hlYXBfYmxvY2tcIlxuICBbQEBub2FsbG9jXVxuXG5sZXQgaXNfb2sgdiA9IGlzX2hlYXBfYmxvY2sgKFN0ZGxpYi5PYmoucmVwciB2KVxubGV0IGNyZWF0ZSB2ID0gaWYgaXNfb2sgdiB0aGVuIFNvbWUgdiBlbHNlIE5vbmVcblxubGV0IGNyZWF0ZV9leG4gdiA9XG4gIGlmIGlzX29rIHYgdGhlbiB2IGVsc2UgZmFpbHdpdGggXCJIZWFwX2Jsb2NrLmNyZWF0ZV9leG4gY2FsbGVkIHdpdGggbm9uIGhlYXAgYmxvY2tcIlxuOztcblxubGV0IHZhbHVlIHQgPSB0XG5sZXQgYnl0ZXNfcGVyX3dvcmQgPSBXb3JkX3NpemUuKG51bV9iaXRzIHdvcmRfc2l6ZSkgLyA4XG5cbmxldCBieXRlcyAodHlwZSBhKSAodCA6IGEgdCkgPVxuICAoU3RkbGliLk9iai5zaXplIChTdGRsaWIuT2JqLnJlcHIgKHQgOiBhIHQpKSArIDEpICogYnl0ZXNfcGVyX3dvcmRcbjs7XG4iXX0=
